FROM nginx:1.13

ADD ./build/vhost.conf /etc/nginx/conf.d/default.conf
ADD ./build/certs /etc/nginx/certs

RUN chown www-data:www-data -R /etc/nginx/certs \
 && chmod -R 600 /etc/nginx/certs \
 && chmod 700 /etc/nginx/certs

RUN useradd --no-log-init -r -m blag
WORKDIR /home/blag/

