version: '2'

services:
  web:
    build:
      context: ./
      dockerfile: docker/web
    volumes:
      - ./:/home/blog
    ports:
      - "8080:80"
    links:
      - app
  app:
    build:
      context: ./
      dockerfile: docker/app
    volumes:
      - ./:/home/blog
    links:
      - db
      - redis
  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - "MYSQL_RANDOM_ROOT_PASSWORD=true"
      - "MYSQL_USER=${DB_USERNAME}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_DATABASE=${DB_DATABASE}"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:mysql
    ports:
      - 8082:80
  redis:
    image: redis:latest
    mem_limit: 500MB

volumes:
  mysql_data:
    driver: local
