version: '2'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.web
    ports:
      - "80:80"
    volumes:
      - code:/home/blag
    links:
      - app
  app:
    build:
      context: ./
      dockerfile: Dockerfile.app 
    volumes:
      - code:/home/blag
    links:
      - db
      - redis
  db:
    image: mysql:5
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - "MYSQL_RANDOM_ROOT_PASSWORD=true"
      - "MYSQL_USER=${DB_USERNAME}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_DATABASE=${DB_DATABASE}"
  redis:
    image: redis:latest
    mem_limit: 500MB
  
volumes:
  mysql_data:
    driver: local
  code:
    driver: local